import type { Project } from "./types";

export const projects: readonly Project[] = [
  {
    id: "blog",
    slug: "blog-tecnico",
    featured: true,
    titleKey: "prj1.t",
    descKey: "prj1.p",
    linkKey: "prj1.link",
    statusKey: "prj1.status",
    status: "live",
    category: "sec",
    url: "https://villacisjimmy.github.io/blog/",
    glyph: "</>",
    tags: ["Security", "Networking", "Writeups"],
  },
  {
    id: "onice",
    slug: "onice-tienda",
    featured: true,
    titleKey: "prj2.t",
    descKey: "prj2.p",
    linkKey: "prj2.link",
    statusKey: "prj2.status",
    status: "live",
    category: "web",
    url: "https://onice.villadev.site",
    glyph: "◆",
    tags: ["Next.js", "Prisma", "Mercado Pago"],
  },
  {
    id: "brava",
    slug: "brava-gastrobar",
    featured: true,
    titleKey: "prj3.t",
    descKey: "prj3.p",
    linkKey: "prj3.link",
    statusKey: "prj3.status",
    status: "live",
    category: "web",
    url: "https://brava.villadev.site",
    glyph: "▦",
    tags: ["NestJS", "Socket.io", "PostgreSQL"],
  },
  {
    id: "vuelve",
    slug: "vuelve-crm",
    featured: true,
    titleKey: "prj4.t",
    descKey: "prj4.p",
    linkKey: "prj4.link",
    statusKey: "prj4.status",
    status: "live",
    category: "web",
    url: "https://vuelve.villadev.site",
    glyph: "↻",
    tags: ["Flask", "PostgreSQL", "WhatsApp API"],
  },
] as const;
