import type { Project } from "./types";

export const projects: readonly Project[] = [
  {
    id: "blog",
    slug: "blog-tecnico",
    featured: true,
    titleKey: "prj1.t",
    descKey: "prj1.p",
    linkKey: "prj1.link",
    statusKey: "prj1.status",
    status: "live",
    category: "sec",
    url: "https://villacisjimmy.github.io/blog/",
    glyph: "</>",
    tags: ["Security", "Networking", "Writeups"],
  },
  {
    id: "n8n",
    slug: "automatizacion-n8n",
    featured: true,
    titleKey: "prj2.t",
    descKey: "prj2.p",
    linkKey: "prj2.link",
    statusKey: "prj2.status",
    status: "soon",
    category: "auto",
    glyph: "⚙",
    tags: ["n8n", "APIs", "Automation"],
  },
  {
    id: "brava",
    slug: "brava-gastrobar",
    featured: true,
    titleKey: "prj3.t",
    descKey: "prj3.p",
    linkKey: "prj3.link",
    statusKey: "prj3.status",
    status: "live",
    category: "web",
    url: "https://brava.villadev.site",
    glyph: "▦",
    tags: ["NestJS", "Socket.io", "PostgreSQL"],
  },
] as const;
